extends: airbnb
plugins:
  - react
  - import
  - jsx-a11y

env:
  browser: yes

rules:
  import/no-extraneous-dependencies: [error, {devDependencies: true}]
  space-before-function-paren: [error, { anonymous: never }]
